### ISSUE TITLE
Exception on 1.21

### ISSUE THREAD

**Issue by Teslicek** [GeyserMC/Floodgate#535] opened 2024-08-18 06:47 UTC
Floodgate b109
UniverseSpigot 1.21 (fork of paper)

```
[08:43:25 WARN]: [floodgate] Task #16684452 for floodgate v2.2.3-SNAPSHOT (b109-49bd564) generated an exception
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:220) ~[?:?]
        at Floodgate #109.jar/org.geysermc.floodgate.skin.SkinDataImpl.<init>(SkinDataImpl.java:45) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.util.SpigotVersionSpecificMethods.currentSkin(SpigotVersionSpecificMethods.java:97) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin0(SpigotSkinApplier.java:80) ~[Floodgate #109.jar:?]
        at Floodgate #109.jar/org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.lambda$applySkin0$0(SpigotSkinApplier.java:63) ~[Floodgate #109.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[universe-1.21.jar:1.21-DEV-a62044c]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[universe-1.21.jar:1.21-DEV-a62044c]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1740) ~[universe-1.21.jar:1.21-DEV-a62044c]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:499) ~[universe-1.21.jar:1.21-DEV-a62044c]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1612) ~[universe-1.21.jar:1.21-DEV-a62044c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1312) ~[universe-1.21.jar:1.21-DEV-a62044c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:335) ~[universe-1.21.jar:1.21-DEV-a62044c]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**Comment by Tim203** [comment] 2024-08-24 12:33
Duplicate of #534

**Closed by Tim203** 2024-08-24 12:33 UTC
