### ISSUE TITLE
Incompatibility with Velocity 422+ build

### ISSUE THREAD

**Issue by bobhenl** [GeyserMC/Floodgate#540] opened 2024-09-03 11:28 UTC
![image](https://github.com/user-attachments/assets/99d960c0-a738-41f3-a00c-bacb29b0f9ff)
seems floodgate is incompatible with other plugins

```yml
[20:35:01 INFO] [limbofilter]: [connected player] Gray_Nebula (/6xxx62131) has client brand vanilla
[20:35:08 ERROR]: java.util.concurrent.CompletionException: java.lang.NullPointerException
[20:35:08 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[20:35:08 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[20:35:08 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
[20:35:08 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[20:35:08 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
[20:35:08 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[20:35:08 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[20:35:08 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[20:35:08 ERROR]: Caused by: java.lang.NullPointerException

[20:38:28 INFO]: [connected player] TYTYBACON (/xxx62954) has disconnected: You were kicked from lifesteal: 
[20:38:28 ERROR]: java.util.concurrent.CompletionException: java.lang.NullPointerException
[20:38:28 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[20:38:28 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[20:38:28 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
[20:38:28 ERROR]:       at java.basejava.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[20:38:28 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
[20:38:28 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[20:38:28 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[20:38:28 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[20:38:28 ERROR]: Caused by: java.lang.NullPointerException
[20:38:28 ERROR]: java.util.concurrent.CompletionException: java.lang.NullPointerException
[20:38:28 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[20:38:28 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[20:38:28 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
[20:38:28 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[20:38:28 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
[20:38:28 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[20:38:28 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[20:38:28 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[20:38:28 ERROR]: Caused by: java.lang.NullPointerException
```

```yml
<html>
<body>
<!--StartFragment-->
[18:52:12] [Netty epoll Worker #1/INFO] [limboapi]: InfinityyyyXD (/**.**.**.**:54861) has connected to the LimboAuth Limbo
--
732 | [18:52:12] [Netty epoll Worker #5/INFO] [limboapi]: InfinityyyyXD (/**.**.**.**:54853) has connected to the LimboAuth Limbo
733 | [18:52:12] [Netty epoll Worker #6/INFO] [limboapi]: InfinityyyyXD (/**.**.**.**:54855) has connected to the LimboAuth Limbo
734 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
735 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
736 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
737 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
738 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
739 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
740 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
741 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
742 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
743 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
744 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.MethodHandleFieldAccessorImpl.ensureObj(MethodHandleFieldAccessorImpl.java:62)
745 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:101)
746 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.reflect.Field.set(Field.java:836)
747 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.util.ReflectionUtils.setValue(ReflectionUtils.java:343)
748 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.addon.data.VelocityProxyDataHandler.setNewIp(VelocityProxyDataHandler.java:117)
749 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.addon.data.CommonDataHandler.lambda$handle$0(CommonDataHandler.java:101)
750 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
751 | [18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	... 5 more
752 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
753 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
754 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
755 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
756 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
757 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
758 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
759 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
760 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
761 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
762 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.MethodHandleFieldAccessorImpl.ensureObj(MethodHandleFieldAccessorImpl.java:62)
763 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:101)
764 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.reflect.Field.set(Field.java:836)
765 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.util.ReflectionUtils.setValue(ReflectionUtils.java:343)
766 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.addon.data.VelocityProxyDataHandler.setNewIp(VelocityProxyDataHandler.java:117)
767 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.addon.data.CommonDataHandler.lambda$handle$0(CommonDataHandler.java:101)
768 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
769 | [18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	... 5 more
770 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
771 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
772 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
773 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
774 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
775 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
776 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
777 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
778 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
779 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
780 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.MethodHandleFieldAccessorImpl.ensureObj(MethodHandleFieldAccessorImpl.java:62)
781 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:101)
782 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.reflect.Field.set(Field.java:836)
783 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.util.ReflectionUtils.setValue(ReflectionUtils.java:343)
784 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.addon.data.VelocityProxyDataHandler.setNewIp(VelocityProxyDataHandler.java:117)
785 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.addon.data.CommonDataHandler.lambda$handle$0(CommonDataHandler.java:101)
786 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
787 | [18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	... 5 more

<!--EndFragment-->
</body>
</html>
[18:52:12] [Netty epoll Worker #1/INFO] [limboapi]: InfinityyyyXD (/**.**.**.**:54861) has connected to the LimboAuth Limbo
[18:52:12] [Netty epoll Worker #5/INFO] [limboapi]: InfinityyyyXD (/**.**.**.**:54853) has connected to the LimboAuth Limbo
[18:52:12] [Netty epoll Worker #6/INFO] [limboapi]: InfinityyyyXD (/**.**.**.**:54855) has connected to the LimboAuth Limbo
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.MethodHandleFieldAccessorImpl.ensureObj(MethodHandleFieldAccessorImpl.java:62)
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:101)
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.reflect.Field.set(Field.java:836)
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.util.ReflectionUtils.setValue(ReflectionUtils.java:343)
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.addon.data.VelocityProxyDataHandler.setNewIp(VelocityProxyDataHandler.java:117)
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.addon.data.CommonDataHandler.lambda$handle$0(CommonDataHandler.java:101)
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[18:52:12] [pool-9-thread-2/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	... 5 more
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.MethodHandleFieldAccessorImpl.ensureObj(MethodHandleFieldAccessorImpl.java:62)
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:101)
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.reflect.Field.set(Field.java:836)
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.util.ReflectionUtils.setValue(ReflectionUtils.java:343)
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.addon.data.VelocityProxyDataHandler.setNewIp(VelocityProxyDataHandler.java:117)
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.addon.data.CommonDataHandler.lambda$handle$0(CommonDataHandler.java:101)
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[18:52:12] [pool-9-thread-4/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	... 5 more
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1[773](https://mclo.gs/yoeIoEO#L773))
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.MethodHandleFieldAccessorImpl.ensureObj(MethodHandleFieldAccessorImpl.java:62)
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:101)
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.reflect.Field.set(Field.java:836)
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.util.ReflectionUtils.setValue(ReflectionUtils.java:343)
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.addon.data.VelocityProxyDataHandler.setNewIp(VelocityProxyDataHandler.java:117)
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.geysermc.floodgate.addon.data.CommonDataHandler.lambda$handle$0(CommonDataHandler.java:101)
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[18:52:12] [pool-9-thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	... 5 more
```

**Comment by Camotoy** [comment] 2024-09-03 23:35
I can connect fine with the latest Velocity build. Does this persist on the latest build for you?

**Comment by Tim203** [comment] 2024-09-04 12:41
I have seen this issue before myself (see #486) but it was really rare. This one seems much more spammy.
Can you try it with just Floodgate and Geyser, and remove all the other plugins? Looks like it might be a plugin conflict with perhaps LimboAuth.

**Comment by Tim203** [comment] 2024-11-02 11:39
Duplicate of #486, if attempts are made to make this issue reproducible please post that in that issue instead.

**Closed by Tim203** 2024-11-02 11:39 UTC
Labels: needs more info
