### ISSUE TITLE
Ability to link other players.

### ISSUE THREAD

**Issue by irishgreencitrus** [GeyserMC/Floodgate#109] opened 2021-01-25 19:57 UTC
I'm a server admin and i'd like the ability to link other players with something like /linkaccount <gamertag> <javausername>. It'd kick both the players if they were online, and obviously only able to be used by ops or someone with a permission of link others.

**Comment by Tim203** [comment] 2021-01-25 20:53
Duplicate of #41

**Closed by Tim203** 2021-01-25 20:53 UTC
