### ISSUE TITLE
Duplicate handler name: floodgate-init

### ISSUE THREAD

**Issue by PappoYT** [GeyserMC/Floodgate#279] opened 2022-03-08 07:46 UTC
I get this error in console:

```
[06:13:21] [Server thread/INFO]: [floodgate] Enabling floodgate v2.1.0-SNAPSHOT
[06:13:21] [Server thread/WARN]: java.lang.IllegalArgumentException: Duplicate handler name: floodgate-init
[06:13:21] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1055)
[06:13:21] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:284)
[06:13:21] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:160)
[06:13:21] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:152)
[06:13:21] [Server thread/WARN]: 	at floodgate-spigot-64.jar//org.geysermc.floodgate.inject.spigot.SpigotInjector.injectClient(SpigotInjector.java:105)
[06:13:21] [Server thread/WARN]: 	at floodgate-spigot-64.jar//org.geysermc.floodgate.inject.spigot.SpigotInjector.inject(SpigotInjector.java:88)
[06:13:21] [Server thread/WARN]: 	at floodgate-spigot-64.jar//org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:121)
[06:13:21] [Server thread/WARN]: 	at floodgate-spigot-64.jar//org.geysermc.floodgate.SpigotPlatform.enable(SpigotPlatform.java:48)
[06:13:21] [Server thread/WARN]: 	at floodgate-spigot-64.jar//org.geysermc.floodgate.SpigotPlugin.onEnable(SpigotPlugin.java:66)
[06:13:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[06:13:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[06:13:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[06:13:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[06:13:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[06:13:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666)
[06:13:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433)
[06:13:21] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[06:13:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1165)
[06:13:21] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[06:13:21] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

Log file: [https://mclo.gs/FViscTx](https://mclo.gs/FViscTx)

**Comment by Tim203** [comment] 2022-03-08 07:51
Duplicate of #38

**Closed** 2022-03-08 07:52 UTC

**Comment by aalprince334** [comment] 2023-07-15 06:58
Remove Keyfile from the floodgate config folder only you need the keyfile in your Geyser-Spigot Config Folder
