### ISSUE TITLE
Floodgate 2.0    [send-floodgate-data]    player not connecting

### ISSUE THREAD

**Issue by ChiAkuma** [GeyserMC/Floodgate#145] opened 2021-05-15 03:06 UTC
Hello if i use floodgate 2.0 and enable the option send-floodgate-data: true then the player is not going to connect
instead there is a whole lot of error

[latest.log](https://github.com/GeyserMC/Floodgate/files/6481809/latest.log)

without the option it works but then i cannot detect if player is a bedrock player.
i have floodgate 2 in the paper server too just to be safe

Im using Velocity (1.1.5) as proxy,
tuinity-paper         ( Tuinity version git-Tuinity-"1382473" (MC: 1.16.5) )

more information:
(my config files)

[floodgate.config.txt](https://github.com/GeyserMC/Floodgate/files/6481813/floodgate.config.txt) (rename to config.yml)
[geyser.config.txt](https://github.com/GeyserMC/Floodgate/files/6481814/geyser.config.txt) (rename to config.yml)
[velocity.toml.txt](https://github.com/GeyserMC/Floodgate/files/6481816/velocity.toml.txt) (rename to velocity.toml)

and if you need more i can send you the whole testing server if you like ;)

**Comment by Konicai** [comment] 2021-05-15 03:13
floodgate's `send-floodgate-data` currently doesn't work if you have velocity's `player-info-forwarding-mode` set to modern 

duplicate of https://github.com/GeyserMC/Floodgate/issues/33

**Comment by Camotoy** [comment] 2021-05-15 03:13
Thanks anyway!

**Closed by Camotoy** 2021-05-15 03:13 UTC

**Comment by ChiAkuma** [comment] 2021-05-15 03:27
Hmm ok i had got managed to use Floodgate 1 with modern.
But i have tested floodgate 2 with none. Maybe ill try legacy and say if it is working for me ;)
