### ISSUE TITLE
Velocity Plugin asking for Java login

### ISSUE THREAD

**Issue by jkcoxson** [GeyserMC/Floodgate#86] opened 2020-12-13 22:33 UTC
Hello all! There is an issue with the Velocity plugin where it will ask for a Java Edition login about 50% of the time when I have the floodgate plugin installed.

Video showing the bug, skip to 0:35
https://drive.google.com/file/d/1QFaTN9Iz8fxGXo3IDQeEVGEFqQnxOWYM/view?usp=sharing

![image](https://user-images.githubusercontent.com/28877351/102025938-46d96200-3d58-11eb-9610-e222aa6bea01.png)

![image](https://user-images.githubusercontent.com/28877351/102025943-58bb0500-3d58-11eb-9cdc-15106c01989b.png)

![image](https://user-images.githubusercontent.com/28877351/102025949-65d7f400-3d58-11eb-9f85-80177955d018.png)

https://dump.geysermc.org/VIOCU2p1wtAg9VlRpRLM9wyvj8klqAps

Anything else you guys need?

**Comment by Camotoy** [comment] 2020-12-13 22:35
Are you able to try with another Java version?

**Comment by jkcoxson** [comment] 2020-12-13 22:36
Like another server version or different software?

**Comment by Camotoy** [comment] 2020-12-13 22:38
Another Java software version. This is not a server issue since the Java prompt should only be triggered if the Geyser config is set to online mode, and isn't influenced by the backend servers.

**Comment by jkcoxson** [comment] 2020-12-13 22:41
I only get this issue on bedrock. What Java software do you want me to change?

**Comment by AwesomestCode** [comment] 2020-12-14 01:18
He wants you to change the version of Java, not *Minecraft: Java Edition*. For example, if you're on Java 8, update to Java 11.

**Comment by jkcoxson** [comment] 2020-12-14 01:22
Oh okay. I'm using Java 11 right now.

**Comment by Camotoy** [comment] 2020-12-14 01:22
That is what I meant; thank you for the clarification. Though in this case, you're using Java 11, so I'm wondering if it's some weird bug with that. Perhaps try Java 8? (As that is what we primarily target at this time)

**Comment by jkcoxson** [comment] 2020-12-14 02:15
Switching to Java 8 fixed it, although I don't think this issue should be closed as this is still a bug. But, I'm not a dev here so do whatever you want.

**Comment by Camotoy** [comment] 2020-12-14 02:16
Yeah, I will not be closing this issue.

**Comment by Camotoy** [comment] 2020-12-14 21:11
I was not able to replicate this bug with Java 11.0.9. Where did you download Java from?

**Comment by jkcoxson** [comment] 2020-12-14 21:12
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode)

Just apt-get I'm pretty sure

**Comment by Camotoy** [comment] 2020-12-14 21:21
Oddly enough, on that exact Java version I connected with Floodgate both times.

**Comment by jkcoxson** [comment] 2020-12-14 21:22
Did you try connecting multiple times? This issue only happens about half of the time.

**Comment by Camotoy** [comment] 2020-12-14 21:22
I will try repeatedly later.

**Comment by Tim203** [comment] 2020-12-18 17:13
Can you also send a console log?

**Comment by Tim203** [comment] 2021-01-12 10:39
Any update on this?

**Comment by jkcoxson** [comment] 2021-01-12 13:59
I've been using the new Java just fine since now. Would you like me to test the older version of Java again?

**Comment by Camotoy** [comment] 2021-01-12 15:38
No need for you to - I can handle that, as I still have your Java version.

**Comment by jkcoxson** [comment] 2021-01-12 16:12
Well, I couldn't figure out how to make the Java command use 8 instead of 11 so I'm just launching Java from the bin folder I built it in lol. If I do get time, I will try it out as you were unable to get the issue in the first place.

**Comment by Camotoy** [comment] 2021-01-20 00:15
I finally got around to testing this multiple times (five) and not once did I get a login prompt.

**Comment by jkcoxson** [comment] 2021-01-21 17:31
Hmmm, could it be that I'm using the velocity version?

**Comment by Tim203** [comment] 2021-01-21 20:08
I expect that Camotoy tested it with the Velocity version

**Comment by Camotoy** [comment] 2021-01-21 20:11
That is correct - I attempted to replicate your complete setup. The only difference besides potentially Java launch arguments was the Velocity version (I used a 1.1.3 snapshot version, I believe).

**Comment by Tim203** [comment] 2021-02-20 18:27
I'm going to close this issue since I haven't heard of any similar situations and Camotoy wasn't able to reproduce it.

**Closed by Tim203** 2021-02-20 18:27 UTC
Labels: question

**Comment by jkcoxson** [comment] 2021-02-20 21:47
Yes, I am unable to produce as well anymore, so maybe a fluke?
