### ISSUE TITLE
Fwhitelist add Error

### ISSUE THREAD

**Issue by NiceygyLive** [GeyserMC/Floodgate#455] opened 2023-09-26 15:14 UTC
When running `fwhitelist add USERNAME` Floodgate spits out the following:

`[15:10:00 ERROR]: [floodgate] An unexpected error happened while executing the whitelist command
java.lang.IllegalStateException: WhitelistStateUpdateEvent may only be triggered synchronously.
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42) ~[purpur-1.20.1.jar:git-Purpur-2050]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2050]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.UserWhiteList.add(UserWhiteList.java:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftOfflinePlayer.setWhitelisted(CraftOfflinePlayer.java:154) ~[purpur-1.20.1.jar:git-Purpur-2050]
        at org.geysermc.floodgate.util.WhitelistUtils.addPlayer(WhitelistUtils.java:53) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.util.SpigotCommandUtil.whitelistPlayer(SpigotCommandUtil.java:125) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.platform.command.CommandUtil.whitelistPlayer(CommandUtil.java:197) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.command.WhitelistCommand.lambda$performCommand$2(WhitelistCommand.java:162) ~[floodgate-spigot.jar:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Geyer Version: V303 (25/09/23)
Floodgate Version: V69 (17/08/23)
MC Java 1.20.1 (Purpur V.2050)

**Comment by Kas-tle** [comment] 2023-09-26 15:24
Duplicate of https://github.com/GeyserMC/Floodgate/issues/444
Please follow there. Thanks!

**Closed by Kas-tle** 2023-09-26 15:24 UTC
