### ISSUE TITLE
Java 8 support missing

### ISSUE THREAD

**Issue by rcmaehl** [GeyserMC/Floodgate#40] opened 2020-06-08 13:07 UTC
According to GeyserMC chat, one of the reasons I'm unable to get Floodgate working on my server is because I'm missing java 7. Since Minecraft 1.12.2 and newer requires Java 8 to run can we see support for Java 8 added?

[SEVERE] Jun 08, 2020 12:17:59 AM com.fasterxml.jackson.databind.ext.Java7Support <clinit> WARNING: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added

**Comment by Heath123** [comment] 2020-06-08 13:08
That's a bug, you can ignore that message. It doesn't mean anything. Geyser works on (and might even need) Java 8 and higher.

**Comment by rcmaehl** [comment] 2020-06-08 13:12
I can't ignore it because Geyser-bungee doesn't seem to work once I install floodgate-bungee. It reports its listening on the port but doesn't. The only 2 other errors I have are

[SEVERE] [floodgate-bungee] The required class to load the SQLite database wasn't found

[SEVERE] Jun 08, 2020 12:18:01 AM org.reflections.Reflections scan
INFO: Reflections took 164 ms to scan 1 urls, producing 29 keys and 281 values

**Comment by Heath123** [comment] 2020-06-08 13:13
Try using https://github.com/GeyserMC/Floodgate/pull/30
Also, if you can please join our Discord for support: https://discord.geysermc.org

**Comment by Tim203** [comment] 2020-06-08 14:24
Duplicate of #30 and #19

**Closed by Tim203** 2020-06-08 14:24 UTC
