### ISSUE TITLE
Floodgate 2.0 failing to enable on Paper 1.17 

### ISSUE THREAD

**Issue by Hellohi3654** [GeyserMC/Floodgate#161] opened 2021-06-17 13:33 UTC
Hi 
I can't get floodgate to work on paper 1.17 
I was working fine on spigot 1.17

Error: 
[13:27:09] [Server thread/INFO]: [floodgate] Enabling floodgate v2.0-SNAPSHOT
[13:27:09] [Server thread/ERROR]: Error occurred while enabling floodgate v2.0-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at org.geysermc.floodgate.inject.spigot.SpigotInjector.getServerConnection(SpigotInjector.java:160) ~[?:?]
	at org.geysermc.floodgate.inject.spigot.SpigotInjector.inject(SpigotInjector.java:59) ~[?:?]
	at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:124) ~[?:?]
	at org.geysermc.floodgate.SpigotPlatform.enable(SpigotPlatform.java:48) ~[?:?]
	at org.geysermc.floodgate.SpigotPlugin.onEnable(SpigotPlugin.java:62) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-"3740db0"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-"3740db0"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-"3740db0"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-"3740db0"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-"3740db0"]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:642) ~[patched_1.17.jar:git-Paper-"3740db0"]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.17.jar:git-Paper-"3740db0"]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"3740db0"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.jar:git-Paper-"3740db0"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.LoginListener$LoginHandler
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrThrow(ReflectionUtils.java:93) ~[?:?]
	at org.geysermc.floodgate.util.ClassNames.getClassOrFallBack(ClassNames.java:210) ~[?:?]
	at org.geysermc.floodgate.util.ClassNames.<clinit>(ClassNames.java:180) ~[?:?]
	... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.LoginListener$LoginHandler
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:157) ~[patched_1.17.jar:git-Paper-"3740db0"]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.17.jar:git-Paper-"3740db0"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.geysermc.floodgate.util.ReflectionUtils.getClassOrThrow(ReflectionUtils.java:91) ~[?:?]
	at org.geysermc.floodgate.util.ClassNames.getClassOrFallBack(ClassNames.java:210) ~[?:?]
	at org.geysermc.floodgate.util.ClassNames.<clinit>(ClassNames.java:180) ~[?:?]
	... 15 more
[13:27:09] [Server thread/INFO]: [floodgate] Disabling floodgate v2.0-SNAPSHOT

**Comment by Camotoy** [comment] 2021-06-17 13:35
Duplicate of #160 - Paper is aware and they should have a fix soon. Thank you!

**Closed by Camotoy** 2021-06-17 13:35 UTC
