### ISSUE TITLE
Server crash when floodgate players join

### ISSUE THREAD

**Issue by noiverre** [GeyserMC/Floodgate#418] opened 2023-06-08 12:17 UTC
```[20:07:58] [epollEventLoopGroup-3-1/INFO]: /180.248.137.241:61078 tried to connect!
[20:07:59] [epollEventLoopGroup-3-3/INFO]: Player connected with username Schwartz441
[20:07:59] [epollEventLoopGroup-5-2/INFO]: Schwartz441 (logged in as: Schwartz441) has connected to remote java server on address 172.18.0.9
[20:08:00] [pool-6-thread-2/INFO]: Floodgate player who is logged in as .Schwartz441 00000000-0000-0000-0009-01f98bc0099c joined
[20:08:00] [Server thread/INFO]: .Schwartz441[/180.248.137.241:52023] logged in with entity id 264 at (788.5, 85.0, 207.5)
[20:08:00] [Server thread/INFO]: Floodgate player logged in as .Schwartz441 joined (UUID: 00000000-0000-0000-0009-01f98bc0099c)
[20:08:00] [Server thread/INFO]: .Schwartz441 joined the game
[20:08:00] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalAccessError: class org.geysermc.floodgate.pluginmessage.FabricSkinApplier tried to access private field net.minecraft.class_1297.field_6002 (org.geysermc.floodgate.pluginmessage.FabricSkinApplier and net.minecraft.class_1297 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3c09711b)
        at org.geysermc.floodgate.pluginmessage.FabricSkinApplier.lambda$applySkin$0(FabricSkinApplier.java:36) ~[floodgate-fabric.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:7318) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:08:00] [Server thread/ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2023-06-08_20.08.00-server.txt
```

Fabric server 1.20, list of mods:
![image](https://github.com/GeyserMC/Floodgate/assets/77881970/c5ce92e9-92f1-46ac-8a44-732a2aba8a55)

**Comment by onebeastchris** [comment] 2023-06-08 12:19
Duplicate of https://github.com/GeyserMC/Floodgate-Fabric/issues/94 - thanks anyways.

There's an open PR to fix this bug, for now, if you have access to the Geyser discord, try the builds linked here:
https://discord.com/channels/613163671870242838/613168464634576897/1116165681986146344
https://discord.com/channels/613163671870242838/613168464634576897/1116181735533719553

**Closed** 2023-06-08 12:20 UTC
Labels: duplicate
