### ISSUE TITLE
LinkageError : loader constraint violation: when resolving interface method 'boolean org.geysermc.floodgate.api.FloodgateApi.sendForm(java.util.UUID, org.geysermc.cumulus.util.FormBuilder)'

### ISSUE THREAD

**Issue by wifi-left** [GeyserMC/Floodgate#369] opened 2022-11-23 06:41 UTC
# Logs
```
14:19:43 [严重] [.wifi_left] -> UpstreamBridge - encountered exception
java.lang.LinkageError: loader constraint violation: when resolving interface method 'boolean org.geysermc.floodgate.api.FloodgateApi.sendForm(java.util.UUID, org.geysermc.cumulus.util.FormBuilder)' the class loader net.md_5.bungee.api.plugin.PluginClassloader @f6c03cb of the current class, me/gamom/commandServers, and the class loader net.md_5.bungee.api.plugin.PluginClassloader @1b7332a7 for the method's defining class, org/geysermc/floodgate/api/FloodgateApi, have different Class objects for the type org/geysermc/cumulus/util/FormBuilder used in the signature (me.gamom.commandServers is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @f6c03cb, parent loader 'app'; org.geysermc.floodgate.api.FloodgateApi is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @1b7332a7, parent loader 'app')
    at me.gamom.commandServers.execute(commandServers.java:96)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:207)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:157)
    at net.md_5.bungee.connection.UpstreamBridge.handleChat(UpstreamBridge.java:188)
    at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:169)
    at net.md_5.bungee.protocol.packet.ClientCommand.handle(ClientCommand.java:77)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
    at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
    at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
    at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:833)
```
I'm using Geyser as well as Flootgate as a dependency library development.
```
FloodgateApi Fapi = FloodgateApi.getInstance();
ProxiedPlayer Pplayer = (ProxiedPlayer) commandSender;
UUID senderUUID = Pplayer.getUniqueId();
boolean isBEPlayer = Fapi.isFloodgatePlayer(senderUUID);
SimpleForm.Builder CForm = SimpleForm.builder()
                .title("A").content("B");
CForm = CForm.responseHandler((arg0) -> {
                System.out.println(arg0);
            });
            Fapi.sendForm(senderUUID, CForm);
```

**Comment by Tim203** [comment] 2022-11-23 09:25
This is a duplicate of #178 and unfortunately we don't really have a solution for that yet.

**Closed by Tim203** 2022-11-23 09:25 UTC

**Comment by Jens-Co** [comment] 2022-11-23 16:37
https://github.com/kejonaMC/Floodgate You can use this fork of floodgate which solves this issue :) do know that this is a fork and not a release from GeyserMC
