### ISSUE TITLE
Floodgate & Protocolize compatility BUG

### ISSUE THREAD

**Issue by OverBrave** [GeyserMC/Floodgate#221] opened 2021-11-01 13:57 UTC
Everything works fine, no problems.

However, after installing the "Protocolize" plugin, Floodgate cannot assign a character to the name of players connecting from Bedrock. In short, it cannot put Prefix. What exactly is the problem?

I opened the same error on their side, but I had to open it here as there might be a compatibility issue.

https://github.com/Exceptionflug/protocolize/issues/103

**Comment by Camotoy** [comment] 2021-11-01 13:58
Can you please send a Geyser dump?

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by OverBrave** [comment] 2021-11-01 14:00
Sure

https://dump.geysermc.org/z0SwH9xxwclpLPIWxYsU2bMguLQani3W

**Comment by Tim203** [comment] 2021-11-02 19:09
It looks like the developer(s) of Protocolize are aware of the issue and try to solve it as soon as they can.
I'm hereby closing this issue, as it appears to be a Protocolize issue.

**Closed by Tim203** 2021-11-02 19:09 UTC

**Comment by KotlinFactory** [comment] 2021-11-02 19:27
I don't see how this is a Protocolize issue.

**Comment by Camotoy** [comment] 2021-11-02 19:29
Can you go into detail on why you think that? I haven't yet looked into the issue.

**Comment by Exceptionflug** [comment] 2021-11-06 13:25
Hey I'm the developer of Protocolize.

The problem relates to the overridden velocity channel initializers. Protocolize and Floodgate are concurrently overriding the channel initializers which causes one of both plugins to fail in functionality. As I've seen your usage of this, you are trying to manipulate the login packet for appending the username prefix for bedrock clients. A possible way to fix this issue is to add proper support for Protocolize since Protocolize was exactly developed for such use cases.

You could check at start if Protocolize is enabled and register a packet listener for the handshake packet to manipulate it using Protocolize. If Protocolize is not installed, it falls back to your existing technique. Is this a possibility for you?

**Comment by Tim203** [comment] 2021-11-06 14:37
> The problem relates to the overridden velocity channel initializers. Protocolize and Floodgate are concurrently overriding the channel initializers which causes one of both plugins to fail in functionality.

The difference between Protocolize and Floodgate is that Floodgate respects the old channel initializer (by calling the old channel initializer's initialize when its being initialized) and yours ignores it. Feel free to look at [Floodgate's source code](https://github.com/GeyserMC/Floodgate/blob/master/velocity/src/main/java/org/geysermc/floodgate/inject/velocity/VelocityInjector.java#L51) or a different plugin like [ViaVersion](https://github.com/ViaVersion/ViaVersion/blob/master/velocity/src/main/java/com/viaversion/viaversion/velocity/platform/VelocityViaInjector.java#L59) to see how we do that.

**Comment by Exceptionflug** [comment] 2021-11-06 14:43
Good catch! Will definetely do something similar in Protocolize.

**Comment by Tim203** [comment] 2021-11-06 14:44
I'll contact the development team of Velocity and I'll propose to add an `add` and a `remove` method and I'll propose to deprecate the `get` and the `set` methods to prevent future issues caused by this design choice.

**Comment by Exceptionflug** [comment] 2021-11-07 09:39
Issue resolved in https://github.com/Exceptionflug/protocolize/commit/ea4e2ca518c46b864d1f8789a4599da80e1796e6

**Comment by LittleChest** [comment] 2023-09-18 15:11
The problem occurs again on my server.
```
[15:03:50 ERROR] [dev.simplix.protocolize.velocity.listener.PlayerListener]: It seems like there is an incompatible plugin installed. Velocity channel initializers are overridden by: org.geysermc.floodgate.inject.velocity.VelocityInjector$VelocityChannelInitializer
[15:03:50 ERROR] [dev.simplix.protocolize.velocity.listener.PlayerListener]: Protocolize is unable to work under this circumstances. Please contact the developers of the incompatible plugin and suggest them to call the initChannel method of the ChannelInitializers before overriding them.
```
Dump: https://dump.geysermc.org/CidY2VnksIfyyHEBqZsbGPGfe6mMGbbM
