### ISSUE TITLE
Floodgate prevents my restart script from working

### ISSUE THREAD

**Issue by rycbar0** [GeyserMC/Floodgate#427] opened 2023-07-05 12:01 UTC
Im running a fabric server and have a batch file that auto restarts the server when it crashes/stops.
```batch
@echo off
:Start Server
java -Xmx8G -jar fabric-server-launch.jar nogui
echo (%time%) Server stoped restarting...
timeout 5
goto Start Server
```
however when floodgate is installed and the server stops the console stops responding
![server  stop](https://github.com/GeyserMC/Floodgate/assets/100363533/e6e53bfd-24c7-42f1-9917-7048af393612)
the console is then unrespons to inputs.
if i try to close the window it asks me if i want to cancel CBatchprocess Y/N?
![cancel](https://github.com/GeyserMC/Floodgate/assets/100363533/a2a42627-a229-4e26-83db-24b44a9f53cc)
if answered yes the console window closes if answered no my batch file continous and restarts the server.
![no](https://github.com/GeyserMC/Floodgate/assets/100363533/ef4c619f-d2b5-423f-9e2e-a3bef737af8e)
any idea why the console cant continoue on its own and how to fix it?

OS: windows 10
MC version: fabric 1.20.1
floodgate version: floodgate-fabric build#102

**Comment by onebeastchris** [comment] 2023-07-05 12:03
Duplicate of https://github.com/GeyserMC/Floodgate-Fabric/issues/59 - turn off metrics in floodgate-fabric for a temporary workaround.

**Closed** 2023-07-05 12:03 UTC
