### ISSUE TITLE
Skins aren't applying if using cape o a special skin (like earth one) on offline servers

### ISSUE THREAD

**Issue by IkyMax** [GeyserMC/Floodgate#514] opened 2024-05-19 07:03 UTC
I know what Geyser now needs an extension for capes and other things butthe thing here is what not even bedrock players are able to see the skins with or without that extension, i tough it was maybe skinrestorer but it isn't working with the plugin disabled, it even works with Geyser offline auth mode

**Comment by bolshakoVVV** [comment] 2024-05-26 06:44
SkinsRestorer has nothing to do with this, I encountered the same thing on BungeeCord, after moving to Velocity both bedrock skins and raincoats appeared.

**Comment by Tim203** [comment] 2024-06-10 19:59
Floodgate skins should take priority over the Bedrock skins. This is intended behavior, as the player could be linked to a Java account in which case the player should have that Java account their skin.

**Closed** 2024-11-02 14:04 UTC
