### ISSUE TITLE
Cannot be used in Spigot/Paper/Purpur 1.19

### ISSUE THREAD

**Issue by Fdsfccffc** [GeyserMC/Floodgate#315] opened 2022-06-11 05:47 UTC
I cannot start my server in paper and purpur 1.19 while using floodgate 2.2.0 (2.1.0 either)
![image](https://user-images.githubusercontent.com/32979888/173174777-01662168-9f90-446d-b769-d92eab95aa1a.png)
![image](https://user-images.githubusercontent.com/32979888/173174821-018a3185-3de6-4a47-833b-6913d1574bde.png)
Then the server went to stop.
On other hand, floodgate cannot be used in spigot 1.19 either. It's likely the same issue.
![QQ图片20220611132931](https://user-images.githubusercontent.com/32979888/173174289-36cc4996-6e70-43bf-84ee-2bda4bb8ab09.png)
But in spigot 1.19, the server didn't stop. However, bedrock edition players could not log in. It said "An internal error happened while handling Floodgate data..."
Is this a bug?

**Comment by Tim203** [comment] 2022-06-11 13:05
Duplicate of #314

**Closed by Tim203** 2022-06-11 13:05 UTC
