### ISSUE TITLE
Geyser + Floodgate on Quilt crash.

### ISSUE THREAD

**Issue by Magicrafter13** [GeyserMC/Floodgate#434] opened 2023-08-03 16:47 UTC
Trying to use the latest floodgate on Modrinth along with either the latest (or close to it) version of Geyser crashes in some way. It doesn't actually say anything about a crash but the server just exits.

After some other mods are initialized successfully, this is the final thing output to the terminal:

```
[09:38:21 WARN] [main]: [Quilt Loader] Multiple paths added for '/org/geysermc/floodgate/crypto/Topping.class', but only a single one can be returned!
 - QuiltZipFileSystem[transformed-mod-geyser-fabric.i0] /org/geysermc/floodgate/crypto/Topping.class
 - QuiltZipFileSystem[transformed-mod-floodgate.i0] /org/geysermc/floodgate/crypto/Topping.class
[09:38:21 WARN] [main]: [Quilt Loader] Multiple paths added for '/org/geysermc/floodgate/crypto/FloodgateCipher.class', but only a single one can be returned!
 - QuiltZipFileSystem[transformed-mod-geyser-fabric.i0] /org/geysermc/floodgate/crypto/FloodgateCipher.class
 - QuiltZipFileSystem[transformed-mod-floodgate.i0] /org/geysermc/floodgate/crypto/FloodgateCipher.class
[09:38:21 INFO] [main]: [geyser-fabric] Loading extensions...
[09:38:21 INFO] [main]: [geyser-fabric] Loaded 0 extension(s)
[09:38:21 INFO] [main]: [Fabric Seasons] [Fabric Seasons] Trying to read config file...
[09:38:21 INFO] [main]: [Fabric Seasons] [Fabric Seasons] A config file was found, loading it..
[09:38:21 INFO] [main]: [Fabric Seasons] [Fabric Seasons] Successfully loaded config file.
[09:38:21 WARN] [main]: [Quilt Loader] Multiple paths added for '/org/geysermc/floodgate/crypto/KeyProducer.class', but only a single one can be returned!
 - QuiltZipFileSystem[transformed-mod-geyser-fabric.i0] /org/geysermc/floodgate/crypto/KeyProducer.class
 - QuiltZipFileSystem[transformed-mod-floodgate.i0] /org/geysermc/floodgate/crypto/KeyProducer.class
[09:38:21 WARN] [main]: [Quilt Loader] Multiple paths added for '/org/geysermc/floodgate/crypto/AesKeyProducer.class', but only a single one can be returned!
 - QuiltZipFileSystem[transformed-mod-geyser-fabric.i0] /org/geysermc/floodgate/crypto/AesKeyProducer.class
 - QuiltZipFileSystem[transformed-mod-floodgate.i0] /org/geysermc/floodgate/crypto/AesKeyProducer.class
[09:38:21 WARN] [main]: [Quilt Loader] Multiple paths added for '/org/geysermc/floodgate/crypto/AesCipher.class', but only a single one can be returned!
 - QuiltZipFileSystem[transformed-mod-geyser-fabric.i0] /org/geysermc/floodgate/crypto/AesCipher.class
 - QuiltZipFileSystem[transformed-mod-floodgate.i0] /org/geysermc/floodgate/crypto/AesCipher.class
[09:38:21 WARN] [main]: [Quilt Loader] Multiple paths added for '/org/geysermc/floodgate/util/InvalidFormatException.class', but only a single one can be returned!
 - QuiltZipFileSystem[transformed-mod-geyser-fabric.i0] /org/geysermc/floodgate/util/InvalidFormatException.class
 - QuiltZipFileSystem[transformed-mod-floodgate.i0] /org/geysermc/floodgate/util/InvalidFormatException.class
[09:38:21 WARN] [main]: [Quilt Loader] Multiple paths added for '/org/geysermc/floodgate/crypto/Base64Topping.class', but only a single one can be returned!
 - QuiltZipFileSystem[transformed-mod-geyser-fabric.i0] /org/geysermc/floodgate/crypto/Base64Topping.class
 - QuiltZipFileSystem[transformed-mod-floodgate.i0] /org/geysermc/floodgate/crypto/Base64Topping.class
[09:38:22 WARN] [main]: [Quilt Loader] Multiple paths added for '/config.yml', but only a single one can be returned!
 - QuiltZipFileSystem[transformed-mod-geyser-fabric.i0]/config.yml
 - QuiltZipFileSystem[transformed-mod-floodgate.i0]/config.yml
 ```

**Comment by onebeastchris** [comment] 2023-08-03 17:28
Duplicate of https://github.com/GeyserMC/Floodgate-Fabric/issues/7, for quilt specifically, there unfortunately isn't a workaround :/

**Closed** 2023-08-03 17:28 UTC

**Comment by Magicrafter13** [comment] 2023-08-03 17:55
My bad!
