### ISSUE TITLE
fwhitelist does not output to RCON

### ISSUE THREAD

**Issue by Ryhon0** [GeyserMC/Floodgate#319] opened 2022-06-12 13:05 UTC
When sending a command to a server with RCON, the returned message is empty.
I would like to use `fwhitelist add` to whitelist Bedrock users on my server when they log in with a MS account on my website but I don't have a way to tell if the command was successful

**Comment by Tim203** [comment] 2022-06-18 09:25
Duplicate of #261

**Closed by Tim203** 2022-06-18 09:25 UTC
