### ISSUE TITLE
Floodgate doesn't work on purpur 1.20.2

### ISSUE THREAD

**Issue by Dreandor** [GeyserMC/Floodgate#454] opened 2023-09-26 08:35 UTC
[10:16:59] [Server thread/INFO]: [floodgate] Enabling floodgate v2.2.2-SNAPSHOT (b69-492be77)
[10:16:59] [Server thread/ERROR]: Error occurred while enabling floodgate v2.2.2-SNAPSHOT (b69-492be77) (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at org.geysermc.floodgate.inject.spigot.SpigotInjector.getServerConnection(SpigotInjector.java:173) ~[floodgate-spigot.jar:?]
	at org.geysermc.floodgate.inject.spigot.SpigotInjector.inject(SpigotInjector.java:62) ~[floodgate-spigot.jar:?]
	at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:71) ~[floodgate-spigot.jar:?]
	at org.geysermc.floodgate.SpigotPlugin.onEnable(SpigotPlugin.java:71) ~[floodgate-spigot.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.2.jar:git-Purpur-2064]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.2.jar:git-Purpur-2064]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:658) ~[purpur-1.20.2.jar:git-Purpur-2064]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:569) ~[purpur-1.20.2.jar:git-Purpur-2064]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:630) ~[purpur-1.20.2.jar:git-Purpur-2064]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.20.2.jar:git-Purpur-2064]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.20.2.jar:git-Purpur-2064]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[purpur-1.20.2.jar:git-Purpur-2064]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[purpur-1.20.2.jar:git-Purpur-2064]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: initUUID from LoginListener cannot be null
	at org.geysermc.floodgate.shadow.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[floodgate-spigot.jar:?]
	at org.geysermc.floodgate.util.ClassNames.checkNotNull(ClassNames.java:235) ~[floodgate-spigot.jar:?]
	at org.geysermc.floodgate.util.ClassNames.<clinit>(ClassNames.java:157) ~[floodgate-spigot.jar:?]
	... 16 more
[10:16:59] [Server thread/INFO]: [floodgate] Disabling floodgate v2.2.2-SNAPSHOT (b69-492be77)

**Comment by Jochem-W** [comment] 2023-10-03 10:10
I think your Floodgate might be outdated, because it seems to work just fine for me using the following:
- Purpur: `git-Purpur-2068 (MC: 1.20.2)`
- Geyser: `2.2.0-SNAPSHOT (git-master-7983448)`
- Floodgate: `2.2.2-SNAPSHOT (b75-26c11bd) (branch: master)`

**Comment by Tim203** [comment] 2023-11-02 20:58
Duplicate of #451

**Closed by Tim203** 2023-11-02 20:58 UTC
