### ISSUE TITLE
Bedrock player cannot join due to "connection closed"

### ISSUE THREAD

**Issue by Conbrown1533** [GeyserMC/Floodgate#267] opened 2022-02-02 23:40 UTC
![Screenshot 2022-02-02 171859](https://user-images.githubusercontent.com/56775379/152256087-dc87b349-8e52-455d-9101-e9ab08802f6e.png)
A player on bedrock cannot connect to the server. I asked another to attempt to connect, but he was also unable to. This is part of the log.

**Comment by Konicai** [comment] 2022-02-02 23:48
This should be fixed with the latest build of floodgate. Regardless, the issue is tracked here: https://github.com/GeyserMC/Geyser/issues/2802

**Closed by Konicai** 2022-02-02 23:48 UTC
