### ISSUE TITLE
Error dispatching event PostLoginEvent to listener

### ISSUE THREAD

**Issue by albertolarahernandez** [GeyserMC/Floodgate#209] opened 2021-10-03 21:04 UTC
01:01:49 [WARNING] Error dispatching event PostLoginEvent(player=*LlyNova) to listener com.djrapitops.extension.FloodgateBungeeListener@74cd82f1
java.lang.LinkageError: loader constraint violation: when resolving interface method 'org.geysermc.floodgate.util.LinkedPlayer org.geysermc.floodgate.api.player.FloodgatePlayer.getLinkedPlayer()' the class loader net.md_5.bungee.api.plugin.PluginClassloader @5bcb04cb of the current class, com/djrapitops/extension/FloodgateBungeeListener, and the class loader net.md_5.bungee.api.plugin.PluginClassloader @28fd3dc1 for the method's defining class, org/geysermc/floodgate/api/player/FloodgatePlayer, have different Class objects for the type org/geysermc/floodgate/util/LinkedPlayer used in the signature (com.djrapitops.extension.FloodgateBungeeListener is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @5bcb04cb, parent loader 'app'; org.geysermc.floodgate.api.player.FloodgatePlayer is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @28fd3dc1, parent loader 'app')
at com.djrapitops.extension.FloodgateBungeeListener.onLogin(FloodgateBungeeListener.java:62)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:29)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:402)
    at net.md_5.bungee.connection.InitialHandler.finnalyFinishLogin(InitialHandler.java:910)
    at net.md_5.bungee.connection.InitialHandler.lambda$finishLogin$3(InitialHandler.java:893)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Camotoy** [comment] 2021-10-03 21:16
Duplicate of #178. Thanks anyway!

**Closed by Camotoy** 2021-10-03 21:16 UTC
