### ISSUE TITLE
Floodgate-bungee missing SQLite classes

### ISSUE THREAD

**Issue by tlaundal** [GeyserMC/Floodgate#32] opened 2020-05-10 07:12 UTC
The jar for floodgate-bungee (from CI or building myself) seems to be missing the necessary classes for SQLite.

## Steps to reproduce
The following commands starts a fresh BungeeCord server with floodgate-bungee as the only plugin.
```bash
wget https://ci.md-5.net/job/BungeeCord/lastSuccessfulBuild/artifact/bootstrap/target/BungeeCord.jar
mkdir plugins
wget -O plugins/floodgate-bungee.jar https://ci.nukkitx.com/job/GeyserMC/job/Floodgate/job/development/lastSuccessfulBuild/artifact/bungee/target/floodgate-bungee.jar
java -jar BungeeCord.jar 
```
BungeeCord will print the following errors:
```
09:06:07 [INFO] Loaded plugin cmd_find version git:cmd_find:1.15-SNAPSHOT:67c2dfd:1499 by SpigotMC
09:06:07 [SEVERE] mai 10, 2020 9:06:07 AM com.fasterxml.jackson.databind.ext.Java7Support <clinit>
WARNING: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added

09:06:07 [INFO] [floodgate-bungee] Loading Floodgate linked player database...
09:06:07 [SEVERE] [floodgate-bungee] The required class to load the SQLite database wasn't found
09:06:07 [INFO] Loaded plugin floodgate-bungee version 1.0-SNAPSHOT by GeyserMC
```

## Workaround
By downloading a jar with sqlite-jdbc (for example from [here](https://bitbucket.org/xerial/sqlite-jdbc/downloads/)), and merging the contents of that jar into the contents of the floodgate-bungee.jar jar, the plugin starts as expected

## Investigation
I haven't looked much into this, but I found it interesting that the floodgate-bungee jar actually contains native files for sqlite, for example `or/sqlite/native/Linux/x86/libsqlitejdbc.so` - which apparently aren't loaded.
I also think that in a lot of cases, floodagte-bungee will be able to use sqlite-jdbc bundled by other plugins.

**Comment by Tim203** [comment] 2020-05-10 09:19
Thanks for making this issue, but it is a duplicate of #29

**Closed** 2020-05-10 09:20 UTC
Labels: duplicate
